name: CD

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Build - ${{ matrix.targetPlatform }} - Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    environment: Unity build
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 6000.0.23f1
        targetPlatform:
          #- WebGL
          - StandaloneLinux64
          - StandaloneWindows
          - StandaloneOSX
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

      - name: Deploy 🚀
        if: contains(matrix.targetPlatform, 'WebGL')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/WebGL
